[package]
name = "ludwig"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = true
strip = "symbols"
panic = "abort"

[dependencies]
actix-files = "0.6.0-beta.16"
rustls = "0.20.2"
rustls-pemfile = "0.3.0"

[dependencies.actix-web]
version = "4.0.0-rc.2"
features = ["rustls"]
